{{- if not .Values.tls_secret }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-delete-secret
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "6"
    helm.sh/hook-delete-policy: "hook-succeeded,hook-failed"
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-delete-secret
      labels:
        app: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: kubectl
          image: "{{ .Values.kubectl.repository }}:{{ .Values.kubectl.tag }}"
          imagePullPolicy: {{ .Values.kubectl.pullPolicy }}
          command:
            - kubectl
            - --namespace=kube-system
            - delete
            - secret
            - {{ .Release.Name }}-cert
      restartPolicy: OnFailure
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
{{- end }}
