---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: {{ .Values.icp-management-ingress.name }}
  name: {{ .Values.icp-management-ingress.name }}
spec:
  ports:
    - name: https
      port: 8443
      targetPort: 8443
  selector:
    k8s-app: {{ .Values.icp-management-ingress.name }}
