---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}
        component: {{ .Release.Name }}
        release: {{ .Release.Name }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - env:
            - name: CLUSTER_DOMAIN
              value: {{ .Values.cluster_domain }}
            - name: WLP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc_secret }}
                  key: WLP_CLIENT_ID
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          {{- if .Values.fips_enabled }}
          image: "{{ .Values.image_fips.repository }}:{{ .Values.image_fips.tag }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          ports:
            - containerPort:  {{ .Values.httpPort }}
              hostPort: {{ .Values.httpPort }}
            - containerPort: {{ .Values.httpsPort }}
              hostPort: {{ .Values.httpsPort }}
          command:
            - /icp-management-ingress
            {{- if .Values.tls_secret }}
            - --default-ssl-certificate=kube-system/{{ .Values.tls_secret }}
            {{- else }}
            - --default-ssl-certificate=kube-system/{{ .Release.Name }}-cert
            {{- end }}
            - --http-port={{ .Values.httpPort }}
            - --https-port={{ .Values.httpsPort }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: icp-management-ingress
          volumeMounts:
            - mountPath: "/opt/ibm/router/nginx/html/dcos-metadata"
              name: router-ui-config
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: router-ui-config
          configMap:
            name: {{ .Release.Name }}-config
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
