---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster_service: 'true'
    kubernetes.io/name: {{ .Values.ingress.name }}
  name: {{ .Values.ingress.name }}
spec:
  ports:
    - name: https
      port: 8443
      targetPort: 8443
  selector:
    k8s_app: {{ .Values.ingress.name }}
