# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}
        component: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
{{- if .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
{{- end }}
      containers:
        - env:
            - name: ENABLE_IMPERSONATION
              value: "{{ .Values.enable_impersonation }}"
            - name: APISERVER_SECURE_PORT
              value: "{{ .Values.apiserver_secure_port }}"
            - name: OIDC_ISSUER_URL
              valueFrom:
                configMapKeyRef:
                  name: platform-auth-idp
                  key: OIDC_ISSUER_URL
            - name: CLUSTER_DOMAIN
              value: {{ .Values.cluster_domain }}
            - name: HOST_HEADERS_CHECK_ENABLED
              value: "{{ .Values.host_headers_check_enabled }}"
            - name: ALLOWED_HOST_HEADERS
              value: "{{ .Values.allowed_host_headers }}"
            - name: WLP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc_secret }}
                  key: WLP_CLIENT_ID
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: FIPS_ENABLED
          {{- if .Values.fips_enabled }}
              value: "true"
          {{- else }}
              value: "false"
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            {{- if .Values.enable_impersonation }}
            - containerPort: {{ .Values.apiserver_secure_port }}
              hostPort: {{ .Values.apiserver_secure_port }}
            {{- end }}
            - containerPort:  {{ .Values.httpPort }}
          {{- if .Values.hostPort }}
              hostPort: {{ .Values.httpPort }}
          {{- end }}
            - containerPort: {{ .Values.httpsPort }}
          {{- if .Values.hostPort }}
              hostPort: {{ .Values.httpsPort }}
          {{- end }}
          command:
            {{- if .Values.enable_impersonation }}
            - /run.sh
            {{- end }}
            - /icp-management-ingress
            - --default-ssl-certificate=kube-system/{{ .Release.Name }}-tls-secret
            - --http-port={{ .Values.httpPort }}
            - --https-port={{ .Values.httpsPort }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: icp-management-ingress
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          {{- if .Values.enable_impersonation }}
          - mountPath: /var/run/secrets/platform-auth
            name: platform-auth-secret
          {{- end }}
          - mountPath: /var/run/secrets/tls
            name: tls-secret
      volumes:
        {{- if .Values.enable_impersonation }}
        - name: platform-auth-secret
          secret:
            defaultMode: 420
            secretName: platform-auth-secret
        {{- end }}
        - name: tls-secret
          secret:
            defaultMode: 420
            secretName: {{ .Release.Name }}-tls-secret
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
