
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  ui-config.json: |-
      {
         "uiConfiguration":{
            "edition":"{{ .Values.icp_edition }}",
            "cluster_name":"{{ .Values.cluster_domain }}",
            "proxy_ip":"{{ .Values.proxy_external_address }}",
            "access_ip":"{{ .Values.cluster_external_address }}",
            "kube_apiserver_secure_port":"{{ .Values.apiserver_secure_port }}"
         }
      }
