# Licensed Materials - Property of IBM
# 5737-E67
# @ Copyright IBM Corporation 2016, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}
        component: {{ .Release.Name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - env:
            - name: CLUSTER_DOMAIN
              value: {{ .Values.cluster_domain }}
            - name: HOST_HEADERS_CHECK_ENABLED
              value: "{{ .Values.host_headers_check_enabled }}"
            - name: ALLOWED_HOST_HEADERS
              value: "{{ .Values.allowed_host_headers }}"
            - name: HTTPS_PORT
              value: "{{ .Values.httpsPort }}"
            - name: WLP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.oidc_secret }}
                  key: WLP_CLIENT_ID
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: FIPS_ENABLED
          {{- if .Values.fips_enabled }}
              value: "true"
          {{- else }}
              value: "false"
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort:  {{ .Values.httpPort }}
              hostPort: {{ .Values.httpPort }}
            - containerPort: {{ .Values.httpsPort }}
              hostPort: {{ .Values.httpsPort }}
          command:
            - /icp-management-ingress
            {{- if .Values.tls_secret }}
            - --default-ssl-certificate=kube-system/{{ .Values.tls_secret }}
            {{- else }}
            - --default-ssl-certificate=kube-system/{{ .Release.Name }}-tls-secret
            {{- end }}
            - --http-port={{ .Values.httpPort }}
            - --https-port={{ .Values.httpsPort }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: icp-management-ingress
          resources:
{{ toYaml .Values.resources | indent 12 }}
      {{- if not .Values.tls_secret }}
        - name: probe
          image: "{{ .Values.probe.repository }}:{{ .Values.probe.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: /opt/ibm/file-freshness-probe/config
            name: cert-probe-config
          - name: certs
            mountPath: /etc/router/certs
          livenessProbe:
            httpGet:
              path: /health
              port: 9601
            #initialDelaySeconds: 300
            initialDelaySeconds: 1
            periodSeconds: {{ .Values.probe.periodSeconds }}
      volumes:
        - name: cert-probe-config
          configMap:
            name: "{{ .Release.Name }}-cert-probe"
        - name: certs
          secret:
            secretName: "{{ .Release.Name }}-tls-secret"
      {{- end -}}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
