os:
  - linux

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make tool
  - make build
  - make docker-login

script:
  - make image || travis_terminate 1
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
        make release
    fi
