os:
  - linux

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

env:
  global:
    - CICD_HTTP_LOGGING_PORT=30333
    - CICD_LOGGING_SERVER=9.42.134.146
  matrix:
  - TARGET=deploy-amd64-openstack TEST_SUITE=daily
  #- TARGET=deploy-power-openstack TEST_SUITE=daily

before_install:
  - printf "\n9.37.33.37  rtpstack5.rtp.raleigh.ibm.com" | sudo tee -a /etc/hosts
  - source travis-env.sh

install:
  - docker info

before_script:
  - make tool
  - make build
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - |
    if [[ "$TRAVIS_EVENT_TYPE" == "pull_request" ]]; then
        echo "skip testing..."
        #make init
        #make keys
        #make ${TARGET}
        #make ${TARGET}:config
        #make pause
        #make setup-dependencies
        #make run-${TEST_SUITE}-tests
        #make ${TARGET}:clean
    else
        make publish
    fi
after_script:
- make ${TARGET}:clean

after_success:
- make log:pass

after_failure:
- make log:fail

