name: management-ingress
description: Multi Cloud control plane ingress controller
keywords:
- ICP
- ingress
- nginx
- IcpClusterResource
- Network
- Commercial
- Limited
- amd64
- ppc64le
- s390x
version: 3.4.0
tillerVersion: ">=2.12.3"
kubeVersion: ">=1.11.0"
appVersion: "3.4.0"
