# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ibmcom/icp-management-ingress
  tag: 2.2.3
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 200m
    memory: 256Mi

config:
  disable-access-log: 'true'

nodeSelector:
  master: 'true'

tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"

cert:
  issuer:
    name: icp-ca-issuer
    kind: ClusterIssuer
  duration: 300h
  renewBefore: 24h

probe:
  repository: ibmcom/file-freshness-probe
  tag: 0.1.0
  periodSeconds: 10
  port: 9601
  reportWhen: "AnyFileChanged"

## Cluster info
cluster_domain: "cluster.local"
cluster_ca_domain: "mycluster.icp"
oidc_secret: "platform-oidc-credentials"
proxy_address: "127.0.0.1"
cluster_address: "127.0.0.1"

## Whether to enable host header check
host_headers_check_enabled: true
allowed_host_headers: "127.0.0.1 mycluster.icp icp-management-ingress"

## Listening port of nginx backend
httpPort: 8080
httpsPort: 8443

## Whether to use BYOK certificates
# tls_secret: "router-certs"

## Whether to enable fips cipher suites
fips_enabled: false
