# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

icp-managment-ingress:
  name: icp-management-Ingress
  image:
    repository: ibmcom/icp-management-ingress
    tag: 2.2.0
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector:
    role: 'master'

  tolerations:
    - key: "dedicated"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "CriticalAddonsOnly"
      operator: "Exists"

  icp_edition: "Enterprise Edition"
  cluster_domain: "mycluster.icp"
  oidc-secret: "platform-oidc-credentials"
  proxy_external_address: "127.0.0.1"
  cluster_external_address: "127.0.0.1"
  apiserver_secure_port: "8001"
