# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: quay.io/open-cluster-management/management-ingress
  tag: 1.0.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 200m
    memory: 256Mi

config:
  disable-access-log: 'true'
  ssl-ciphers: 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256'

nodeSelector:
  master: 'true'

tolerations:
  - key: "dedicated"
    operator: "Exists"
    effect: "NoSchedule"

cert:
  issuer:
    name: icp-ca-issuer
    kind: ClusterIssuer
  duration: 2160h
  renewBefore: 24h

## Cluster info
cluster_domain: "cluster.local"
cluster_ca_domain: "mycluster.icp"
oidc_secret: "platform-oidc-credentials"
cluster_address: "127.0.0.1"
cluster_internal_address: "127.0.0.1"

## Use BYO cert
# tls_secret: icp-management-ingress-tls-secret

## Whether to enable host header check
host_headers_check_enabled: true
allowed_host_headers: "127.0.0.1 mycluster.icp icp-management-ingress iam-token-service"

## Listening port of nginx backend
httpPort: 8080
httpsPort: 8443

## Use host port
hostPort: true

## Use host network
hostNetwork: false

## Whether to enable fips cipher suites
fips_enabled: false

## Whether to do impersonation
enable_impersonation: false

## Kubernetes port
apiserver_secure_port: 8001

## Is used internally for externally
internal_use: true

imageTagPostfix: ""